@startuml 

skinparam linetype ortho

skinparam component{
  BackgroundColor lightsteelblue
}

skinparam interface{
  BackgroundColor lightskyblue
}
skinparam package{
  BackgroundColor lightsteelblue
}

component Hospital{
    package FrameworksAndDrivers{
      package Routes {

      }
      package Persistence {

      }
    }
    package InterfaceAdaptars{
      package Controllers{
        package Controller{

        }
      }
      package Repositories{
        package ImpRepositories{

        }
      }
    }

    package ApplicationBusinessRules{
      package Services{
        package IServices{

        }
        package ImpServices{

        }
        package IRepositories{

        }
      }
    }

    package EnterpriseBusinessRules{
      package Model{

      }
    }
}

Routes ..> Controller
Controller ..> IServices
ImpServices ..|> IServices
ImpServices ..> IRepositories
ImpRepositories ..|> IRepositories
ImpServices ..> Model
ImpRepositories .up.> Persistence

@enduml
