@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Process View Level 1
autonumber

actor "Admin" as Admin
participant "<<System C4>>" as System

activate Admin
Admin -> System: Request to create a new patient profile
activate System
System --> Admin: Asks patient necessary information
Admin -> System: Provides patient necessary information
System --> Admin: Success/Error message
deactivate Admin



@enduml