@startuml

'skinparam monochrome true
'skinparam packageStyle rectangle
'skinparam shadowing false
'skinparam linetype ortho
'left to right direction
'skinparam classAttributeIconSize 0
'hide circle
hide methods

title Healthcare System Class Diagram

package "<<aggregate>> System_User" {
  class User <<entity>> {}
  class username <<primitive>> {}
  class role <<value object>> {}
  class Roles <<enum>> {
  - admin
  - doctor
  - nurse
  - technician
  - patient
  }
}

package "<<aggregate>> Name" {
  class Name <<value object>> {}
  class firstName <<primitive>> {}
  class lastName <<primitive>> {}
  class fullName <<primitive>> {}
}

package "<<aggregate>> ContactInformation" {
  class contactInformation <<value object>> {}
  class phone <<primitive>> {}
  class email <<root>> {}
}

package "<<aggregate>> Patient" {
  class Patient <<entity>> {}
  class patientID <<root>> {}
  class dateOfBirth <<primitive>> {}
  class gender <<primitive>> {}
  class medicalRecordNumber <<primitive>> {}
  class allergiesMedicalRecord <<primitive>> {}
  class emergencyContact <<primitive>> {}
  class appointmentHistory <<value object>> {}
}

package "<<aggregate>> Appointment" {
  class Appointment <<entity>> {}
  class appointmentID <<root>> {}
  class dateTime <<primitive>> {}
  class status <<primitive>> {}
}

package "<<aggregate>> OperationRequest" {
  class OperationRequest <<entity>> {}
  class requestID <<root>> {}
  class deadLineDate <<primitive>> {}
  class priority <<primitive>> {}
}


package "<<aggregate>> OperationType" {
  class OperationType <<entity>> {}
  class typeID <<root>> {}
  class typeName <<primitive>> {}
  class requiredStaffBySpecialization <<primitive>> {}
  class estimatedDuration <<primitive>> {}
}

package "<<aggregate>> SurgeryRoom" {
  class SurgeryRoom <<entity>> {}
  class roomID <<root>> {}
  class roomNumber <<primitive>> {}
  class roomType <<primitive>> {}
  class capacity <<primitive>> {}
  class assignedEquipment <<primitive>> {}
  class currentStatus <<primitive>> {}
  class maintenenceSlots <<primitive>> {}
}

package "<<aggregate>> TimeSlot" {
  class TimeSlot <<value object>> {}
  class date <<primitive>> {}
  class time <<primitive>> {}
}

package "<<aggregate>> Staff" {
  class Staff <<entity>> {}
  class licenseNumber <<primitive>> {}
  class availabilitySlots <<primitive>> {}

  class Admin <<entity>> {}
  class Doctor <<entity>> {}
  class staffID <<root>> {}
  class Nurse <<entity>> {}
  class Technician <<entity>> {}
}

package "<<aggregate>> Specialization" {
    class specialization <<entity>> {}
    class specializationName <<root>> {}
}

class IAM <<entity>> {}

User --> username
User --> role
User --> userEmail
User <---- Staff
User <--- Patient
role --> Roles 

Name --> fullName
Name --> firstName
Name --> lastName

Patient --> patientID
Patient ---> Name
Patient --> dateOfBirth
Patient --> gender
Patient ---> contactInformation
Patient --> medicalRecordNumber
Patient --> allergiesMedicalRecord
Patient --> emergencyContact
Patient --> appointmentHistory

appointmentHistory <-- Appointment
contactInformation -> phone
email <-- contactInformation

Staff ---> Name
Staff --> licenseNumber
Staff --> specialization
Staff --> contactInformation
Staff --> availabilitySlots
Staff --> Appointment
Staff --> staffID

specialization --> specializationName

Appointment --> dateTime
Appointment --> appointmentID
Appointment --> status
TimeSlot <-- Appointment
requestID <--- Appointment


Appointment ---> roomID : must match availability

requiredStaffBySpecialization <-- specialization : must match specialization

OperationRequest --> requestID
OperationRequest -> staffID : check if doctor
OperationRequest --> patientID
OperationRequest --> typeID
OperationRequest --> deadLineDate
OperationRequest ---> priority

OperationType --> typeName
OperationType --> typeID
OperationType --> requiredStaffBySpecialization
OperationType --> estimatedDuration

SurgeryRoom --> roomNumber
roomID <-- SurgeryRoom
SurgeryRoom --> roomType
SurgeryRoom --> capacity
SurgeryRoom --> assignedEquipment
currentStatus --> SurgeryRoom
SurgeryRoom -> maintenenceSlots

date <- TimeSlot
TimeSlot -> time

Staff <|-- Admin
Staff <|-- Doctor
Staff <|-- Nurse
Staff <|-- Technician

IAM --> User : "authenticates"

@enduml
