name: Deploy C# Backend

on:
  push:
    paths:
      - 'MDR/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy and Restart Backend
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "
          cd /var/www/project/MDR &&
          git pull &&
          dotnet build &&
          pm2 restart backend || pm2 start 'dotnet run --urls=http://0.0.0.0:5001' --name backend
        "
