name: Deploy React SPA

on:
  push:
    paths:
      - 'SPA/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies and Build
      run: |
        cd SPA
        npm install
        CI=false npm run build

    - name: Debug Environment
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        echo "SSH_HOST: $SSH_HOST"
        echo "SSH_USERNAME: $SSH_USERNAME"
        echo "SSH_PRIVATE_KEY length: ${#SSH_PRIVATE_KEY}"

    - name: Test SSH Connection
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "echo Connection Successful"
        
    - name: Test DNS Resolution
      run: nslookup ${{ secrets.SSH_HOST }}

    - name: Deploy to Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      run: |
        scp -r SPA/build/* $SSH_USERNAME@$SSH_HOST:/var/www/html/spa/
        ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$SSH_HOST "sudo systemctl reload apache2"
