name: Deploy C# Backend

on:
  push:
    branches:
      - main
    paths:
      - 'MDR/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy and Restart Backend
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: 10606
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        timeout: 600 # Increased timeout to 10 minutes
        command_timeout: 600
        script: |
          cd /var/www/project/MDR
          git reset --hard
          git pull         
          dotnet build
          pm2 stop backend || true
          pm2 delete backend || true
          pm2 start "dotnet run --project /var/www/project/MDR/sem5pi-24-25-g034.csproj" --name backend
          pm2 save
