name: Deploy React SPA

on:
  push:
    branches:
      - main
    paths:
      - 'SPA/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies and Build Locally
      run: |
        cd SPA
        npm install
        NODE_OPTIONS="--max-old-space-size=4096" npm run build

    - name: Deploy Build to Server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 10606
        source: SPA/build/*
        target: /var/www/project/SPA/
