name: Deploy C# Backend

on:
  push:
    paths:
      - 'MDR/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Deploy and Restart Backend
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        port: 10606
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/project/MDR
          git pull
          dotnet build
          pm2 restart backend || pm2 start 'dotnet run --urls=http://0.0.0.0:5001' --name backend
