name: Deploy React SPA

on:
  push:
    paths:
      - 'SPA/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies and Build
      run: |
        cd SPA
        npm install
        CI=false npm run build

    - name: Deploy to Server with Public SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: vsgate-ssh.dei.isep.ipp.pt
        username: ${{ secrets.SSH_USERNAME }}
        port: 10606
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          mkdir -p /var/www/html/spa/
          rm -rf /var/www/html/spa/*
          cp -r SPA/build/* /var/www/html/spa/
          sudo systemctl reload apache2
