name: Deploy React SPA

on:
  push:
    branches:
      - main
    paths:
      - 'SPA/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: |
        cd SPA
        npm install
        npm install --save-dev @babel/plugin-proposal-private-property-in-object

    - name: Build with Memory Increase and No CI
      run: |
        cd SPA
        CI=false node --max-old-space-size=4096 node_modules/react-scripts/scripts/build.js

    - name: Deploy Build to Server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 10606
        timeout: 1800s
        script: |
          sudo rm -rf /var/www/html/spa/*
          sudo mkdir -p /var/www/html/spa
          sudo cp -r /var/www/project/SPA/build/* /var/www/html/spa/
          sudo systemctl restart apache2
